dist: trusty
language: node_js
node_js:
  - "12.0"
cache:
  directories:
    - ./node_modules
before_install:
  - npm install -g yarn
install:
  - yarn
script:
  - yarn lint
  - yarn test-headless
  - yarn build --prod
